### ISSUE TITLE
Morning session feedback 2/24/2023

### ISSUE THREAD

**Issue by J-C-S-V** [Alejandroq12/portfolio#6]
Hi Julio!

Here are our recommendations so your project can look even better : D

- Let's try to use BEM naming convention for HTML classes.
- For the social logos it was a requirement to use ul and li to wrap those images.
- We suggest you could give a try using rem sometimes instead of pixels.

Good job so far!

**Comment by Alejandroq12** [comment]
Hello, Juan!
Thank you very much for your feedback. I will improve those aspects.
Have a nice day.
