### ISSUE TITLE
Portfolio Website Already Deployed - Adding Link to Online Version

### ISSUE THREAD

**Issue by Alejandroq12** [Alejandroq12/portfolio#8]
## Dear Reviewer.

I am creating this issue to fulfill the project requirement of providing a link to the online version of my portfolio website. I have already deployed my website earlier and, for that reason, I will not be creating a pull request. As instructed in the project description, I am opening this issue and sharing the link to my online portfolio.

- Link to my Portfolio Website: https://alejandroq12.github.io/portfolio/

I have verified that the online version of my website works properly and have also updated the README file of my repository to include this link. Please let me know if you need any further information or clarification.

Thank you.

**Comment by binhussen** [comment]
Hi @Alejandroq12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you! Have an amazing day.
