### ISSUE TITLE
Peer-to-peer code review 28/02/2023

### ISSUE THREAD

**Issue by smunoz1988** [Alejandroq12/portfolio#9]
Julio, great job on the progress you have made so far in your GitHub repository. We believe that you have the potential to produce an excellent product. To improve further, we recommend the following changes: 🤪🤪

- Take considerations in all cards with the hover transitions (button and cards)
- Anchor the tags in the navbar with the "called" section. 
- We recommend that you use SVG's instead of PNG's for your website. SVG's are vector graphics, which means that they scale to any size without losing quality. In contrast, PNG's are raster images that can become blurry when scaled. Low-quality images can result in lower rankings in SEO.

if you have any questions just let us know.

**Comment by Alejandroq12** [comment]
## Thank you very much for your feedback.
-- I fixed almost all of those issues. 
-- Right now I just need to eliminate the .png images and I will use .svg.

Have a very good day. 
Thanks!
